### PR TITLE
More structure & refactor

### PR DESCRIPTION
**Pull request by maddyrandle**
### Type of change made:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] TDD (update test suite)
### Detailed Description
- Continued test suite setup 
    -  Tested that classes are a function and that we can instantiate a new object of the class
    - Added a hook to insert new instantiation and test data beforeEach it block
- Used split() method on the User class to return the first name only
- Updated the parameter name from 'data' to 'userData' on the UserRepository class to be consistent with our parameter name in the Hydration class 'hydrationData'
- Deleted some of the html and css styling that I originally hard coded (after reading in the project spec not to do this)
-  Created function on the script.js file for dom manipulation that inserts html (rough structure/styling) on page load

### Were there any challenges that arose while implementing this feature? If so, how were they addressed?
- I am stumped on how to get the class files to communicate with our script.js file so that we can interpolate the users information.

#### src directory
  - [ ] Activity.js
  - [ ] Hydration.js
  - [ ] Sleep.js
  - [x] User.js
  - [x] UserRepository.js
  - [x] script.js
  - [x] index.html
  - [x] main.css
#### test directory
  - [ ] Activity-test.js
  - [ ] Hydration-test.js
  - [ ] Sleep-test.js
  - [x] User-test.js
  - [x] UserRepository-test.js

### CODE REVIEW

**Comment by CLPena** [comment]
Hey Maddy! This looks like an awesome start. Thanks for working on it! Would you mind updating the project board with what you completed?

I see that you said you're stumped about getting the files to communicate properly. How can you tell that they're not at this point? What have you tried?

**Comment by maddyrandle** [comment]
Yes, I will update the project board now.

As far as getting the files to communicate, I started with requiring the User.js and UserRepository.js together and separately so that when we could pull from one or both of its data to get the users name, etc. I got an error that said "Uncaught ReferenceError: require is not defined".

**Comment by CLPena** [comment]
That's weird. I wonder if it has something to do with the setup. Did you run npm install?

**Comment by maddyrandle** [comment]
I'll try running npm install again, I had run in before though 🤔

A few other things I forgot to mention:
- On the project spec where it says:
    - "A UserRepository holds onto all of the User objects", I'm wondering if we need a method of some sort that takes the userData and pushes it into and array?
    - "It should have a parameter to take in a userData object" also wondering if we need a new class specifically for "userData object"

**Comment by CLPena** [comment]
I'm not sure about those other questions. Let's hold on to them as we move forward, but not worry about them when merging in this branch. We can merge this branch, use it as a starting point, and then break up some tasks to work on individually and specifically (one step at a time!).

**Comment by maddyrandle** [comment]
Sounds great!

**Pull request merged**
